global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-products'
    static_configs:
      - targets: ['host.docker.internal:21401']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']